name: UX/UI Suggestion
description: Sugestão de melhoria na experiência do usuário ou interface
title: "[UX/UI]: "
labels: ["ux/ui"]
body:
  - type: markdown
    attributes:
      value: Obrigado por dedicar seu tempo para preencher esta sugestão de design! Preencha tudo o que puder para garantir que esteja fornecendo o máximo de informações possível, para uma revisão rápida!

  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: "Ao enviar este formulário você concorda em seguir nossas diretrizes: [Código de Conduta](https://github.com/CollabHubBR/.github/blob/main/CODE_OF_CONDUCT.md), [Contribuição](https://github.com/CollabHubBR/.github/blob/main/CONTRIBUTING.md), [Segurança](https://github.com/CollabHubBR/.github/blob/main/SECURITY.md) e [Suporte](https://github.com/CollabHubBR/.github/blob/main/SUPPORT.md)."
      options:
        - label: Eu concordo em seguir as Diretrizes do Projeto.
          required: true

  - type: input
    id: context
    attributes:
      label: Contexto
      description: Descreva o contexto atual da interface ou experiência que você deseja melhorar.
      placeholder: O menu lateral está confuso quando temos muitos itens...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Qual é a sua sugestão?
      description: Explique o que você sugere melhorar ou mudar. Seja específico sobre a interação, aparência ou fluxo.
      placeholder: Reorganizar os itens em categorias para facilitar a navegação...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Qual o benefício esperado?
      description: Por que essa mudança é importante para o usuário ou para o projeto?
      placeholder: Isso tornaria mais rápido encontrar funcionalidades específicas, melhorando a usabilidade.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: Liste outras soluções ou ideias que você pensou antes de chegar a esta sugestão.
      placeholder: ...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots ou Videos
      description: Adicione links para gifs, videos ou materiais extra como referência.
      placeholder: https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdG80aGdxZjNiY3JvMWY1ZzR6dDlsZ3FsejJ3aHdnN2k5MWQ4Y2VvaSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/QMHoU66sBXqqLqYvGO/giphy.gif
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Adicione qualquer outro conteúdo útil à feature apresentada
      placeholder: ...
    validations:
      required: false
